---
instance_name: 'MediaWiki'
subdomain: ''
hostname: '{{ansible_fqdn}}'
mediawiki_dir: ''
mediawiki_path: '/srv/{{instance_name}}'
mediawiki_language: 'en'
# REL1_33 does not work at all with edu-shargin currently and versions >= 1.29.0 removed deprecated api (https://www.mediawiki.org/wiki/Manual:Hooks/ArticleSave) that edu-sharing is using...
# REL1_28 does not work because dependency wikimedia/php-session-serializer": "1.0.4" seems to be gone...
mediawiki_version: REL1_27
server_name: '{% if subdomain %}{{subdomain}}.{% endif %}{{hostname}}'
base_uri: 'http://{{server_name}}/{{mediawiki_dir}}'

mediawiki_skins:
- Vector

admin_user:
  name: root
  pass: admin
mediawiki_db:
  connection: mysql
  name: mw_{{instance_name}}
  user: mw_{{ instance_name | truncate(16-3, True, '') }}
  password: mediawiki
