---

- name: Clone mediawiki
  git:
    repo: 'https://gerrit.wikimedia.org/r/p/mediawiki/core.git'
    dest: '{{ mediawiki_path }}'
    version: "{{mediawiki_version|default('HEAD')}}"
    depth: 1
    force: yes

- include: composer.yml

- name: Install imagemagick
  package:
    name: imagemagick
    state: present

- name: Install mediawiki dependencies
  shell: composer install --no-dev
  args:
    chdir: '{{ mediawiki_path }}'
  # become: no

- include: mysql.yml
  when: mediawiki_db.connection == "mysql"

- name: Install mediawiki skins
  git:
    repo: "https://gerrit.wikimedia.org/r/mediawiki/skins/{{item}}"
    dest: "{{ mediawiki_path }}/skins/{{item}}"
    version: "{{mediawiki_version|default('HEAD')}}"
  with_items: '{{mediawiki_skins}}'

- name: Install mediawiki
  command: php {{ mediawiki_path }}/maintenance/install.php
    --dbname {{mediawiki_db.name}}
    --dbuser {{mediawiki_db.user}}
    --dbpass {{mediawiki_db.password}}
    --dbtype {{mediawiki_db.connection}}
    --lang {{mediawiki_language}}
    --pass {{admin_user.pass}}
    --scriptpath '{{mediawiki_dir}}'
    {{instance_name}} {{admin_user.name}}
  args:
    creates: '{{ mediawiki_path }}/LocalSettings.php'
    
- name: Change owner and group of images directory
  file:
    path: '{{ mediawiki_path }}/images'
    state: directory
    owner: "www-data"
    group: "www-data"
    recurse: yes

- name: Set MediWiki config in nginx
  template:
    src: mediawiki.nginx.conf.jinja2
    dest: /etc/nginx/sites-available/mediawiki

- name: Remove default
  file:
    name: /etc/nginx/sites-available/default
    state: absent

- name: Set LocalSettings.php
  template:
    src: LocalSettings.php
    dest: '{{ mediawiki_path }}/LocalSettings.php'

- include: extensions.yml
  tags: extensions

- name: Enable site
  file:
    src: /etc/nginx/sites-available/mediawiki
    dest: /etc/nginx/sites-enabled/mediawiki
    state: link

- name: Disable default
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart nginx
  service:
    name: nginx
    state: restarted
