---
- name: Install semantic
  shell: composer require mediawiki/semantic-media-wiki "3.0.0" --update-no-dev
  args:
    chdir: '{{ mediawiki_path }}'

- name: Run the maintenance script
  command: php maintenance/update.php --skip-external-dependencies
  become: yes
  args:
    chdir: '{{ mediawiki_path }}'

- name: Enable Semantic MediaWiki
  lineinfile:
    dest: '{{ mediawiki_path }}/LocalSettings.php'
    line: "enableSemantics( 'localhost' );"
    insertafter: 'EOF'
    state: present
