---
- name: Install semantic
  shell: composer require mediawiki/semantic-media-wiki "~2.5" --update-no-dev
  args:
    chdir: '{{ mediawiki_path }}'

- name: Run the maintenance script
  shell: php maintenance/update.php --skip-external-dependencies
  args:
    chdir: '{{ mediawiki_path }}'

- name: Enable Semantic MediaWiki
  lineinfile:
    dest: '{{ mediawiki_path }}/LocalSettings.php'
    line: "enableSemantics( 'localhost' );"
    insertafter: 'EOF'
    state: present
