---

- name: 1. Ensure mysql python packages are present
  package:
    name: python-mysqldb

- name: 2. Create database
  mysql_db:
    name: '{{mediawiki_db.name}}'
    login_unix_socket: '/var/run/mysqld/mysqld.sock'

- name: 3. Create database user
  mysql_user:
    name: '{{mediawiki_db.user}}'
    password: '{{mediawiki_db.password}}'
    priv: '{{mediawiki_db.name}}.*:ALL'
